config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'static_pages#home'

  resources :members do
    resources :skills
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :member
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.sort_by(&:created_at)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    redirect_to members_path
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    Skill.where(:member_id => @member.id).each do |s|
      s.destroy
    end
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :availability, :availability_description)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    redirect_to members_path
  end

  # GET /skills/new
  def new
    @skill = Skill.new(:member_id => params["member_id"])
    @languages = Language.pluck(:id, :description)
  end

  # GET /skills/1/edit
  def edit
    @languages = Language.pluck(:id, :description)
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill.member, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill.member }
      else
        format.html { render :new }
        format.json { render json: @skill.member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill.member, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill.member }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:member_id, :language, :level, :need_practise)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
- Now you are signed in as  <%=current_user.email %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
    <nav>
      <%= link_to "LEN", root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	<li><%= link_to "Members", members_path %></li>
	<li><a href="#">Couples</a></li>
	<li><%= link_to "Log out", destroy_user_session_path, method: "delete"%></li>
	<% else %>
	<li><%= link_to "Log in", new_user_session_path%></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LanguageCanbuildyourWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message | %>
      <div class="alert alert-<%= message_type%>"><%= message %></div>
      
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

<% if @member.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @member.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <%=f.error_span(:name) %>
</div>
<div class="form-group">
  <%= f.label :availability_description, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :availability_description, :class => 'form-control' %>
  </div>
  <%=f.error_span(:availability_description) %>
</div>
<div class="form-group" hidden>
  <%= f.label :availability, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <% if @member["availability"] != nil %>
    <% availability_array = @member["availability"] %>
    <% else %>
    <% availability_array = Array.new(24*7, 0)%>
    <% end %>
    <%= f.text_field :availability, :class => 'form-control', :value => availability_array  %>
  </div>
  <%=f.error_span(:availability) %>
</div>

<div class="form-group table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
	<!-- forloop days-->
	<th></th>
	<% Date::DAYNAMES.rotate.each do |day| %>
	<th><%= day.first(3) %></th>
	<% end %>
	<!-- end for -->
      </tr>
    </thead>
    <tbody>
      <% time = Time.new.beginning_of_day %>
      <% 1.upto(24) do |i| %>
      <!-- 00:00 - 12:00 hidden default unavailable -->
      <% if time < (Time.new.noon - 4.hours) || time > (Time.now.at_end_of_day - 2.hours) %>
	 <% visibility = "hidden" %>
      <% else %>
	 <% visibility = "" %>
      <% end %>
      <tr <%= visibility %>>
	<td><%= time.to_formatted_s(:time) %> - <%= (time+59.minutes).to_formatted_s(:time) %></td>
	<% #TODO οι αριθμοί εν μπακαλλίσιμοι, καλύτερα να οριστούν ή χρησιμοποιηθούν σταθερές %>
	<% 1.upto(7) do |j| %>
	<% check_box_value = ((j-1)*24)+(i-1)%>
	<% check_box_id = Date::DAYNAMES.rotate[j-1].first(3) + "_" +time.to_formatted_s(:time).split(":").join("_")  %>
	<% is_checked = false %>
	<% if @member["availability"] != nil && @member["availability"].split(" ")[check_box_value] == "1" %>
	<% is_checked = true %>
	<% end %>
        <td><%= check_box_tag( check_box_id, check_box_value, is_checked, :onclick => "paintIt(this);") %></td>
	<% end %>
	<!-- endfor -->
      </tr>
      <% time = time + 1.hour %>
      <% end %>
      <!-- endfor -->
    </tbody>
  </table>
  
</div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    members_path, :class => 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> of Language Exchange - Nicosia</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:availability_description) %></th>
      <th><%= model_class.human_attribute_name(:skills) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, edit_member_path(member) %></td>
        <td><%= member.availability_description %></td>
	<% levels_array = ["A1", "A2", "B1", "B2", "C1", "C2", "native", "nothing"]%>
	<td><% Skill.where(member_id: member.id).each do |s| %><span <% if s.need_practise %>class="text-danger"<% end %>><%= link_to s.language, edit_member_skill_path(member, s) %>-<%= levels_array[s.level] %></span> <% end %></td>
        <td>
	  <%= link_to "Add Skill",
              new_member_skill_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @member.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:availability_description) %>:</strong></dt>
  <dd><%= @member.availability_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skills) %>:</strong></dt>
  <% @skills.each do |skill|%>
  <%= skill.language %>,   <%= skill.level %>,  <%= skill.need_practise %>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/skills/_form.html.erb
<%= form_for ([@skill.member, @skill]), :html => { :class => "form-horizontal skill" } do |f| %>

  <% if @skill.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @skill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="form-group" hidden>
    <%= f.label :member_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :member_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:member_id) %>
  </div>
  <div class="form-group">
    <%= f.label :language, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :language, :class => 'form-control', :list => 'languages', :autocomplete => 'off' %>
      <datalist id="languages">
	<%  @languages.each do |l| %>
	<%= content_tag(:option, l.last, value: l.last) %>
	<% end %>
      </datalist>
    </div>
    <%=f.error_span(:language) %>
  </div>
  <div class="form-group">
    <%= f.label :level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <% #TODO define them in a helper %>
      <%= f.select(:level,
	  [['nothing',-1],['A1',0],['A2',1],
	  ['B1',2],['B2',3],
	  ['C1',4],['C2',5],
	  ['native',6]], {},
	  { :class => 'form-control' }) %>
    </div>
    <%=f.error_span(:level) %>
  </div>
  <div class="form-group">
    <%= f.label :need_to_practise, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select(:need_practise, [['No','false'],['Yes','true']], {},{:class => 'form-control'}) %>
    </div>
    <%=f.error_span(:need_practise) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/skills/edit.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %> <%= @skill.language %> for <%= @skill.member.name %></h1>
</div>
<%= render :partial => 'form' %>

app/views/skills/index.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:member_id) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:need_practise) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= link_to skill.id, skill_path(skill) %></td>
        <td><%= skill.member_id %></td>
        <td><%= skill.language %></td>
        <td><%= skill.level %></td>
        <td><%= skill.need_practise %></td>
        <td><%=l skill.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_skill_path(skill), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      skill_path(skill),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_skill_path,
            :class => 'btn btn-primary' %>

app/views/skills/new.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %> for <%= @skill.member.name %></h1>
</div>
<%= render :partial => 'form' %>

app/views/skills/show.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:member_id) %>:</strong></dt>
  <dd><%= @skill.member_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @skill.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @skill.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:need_practise) %>:</strong></dt>
  <dd><%= @skill.need_practise %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              skills_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_skill_path(@skill), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              skill_path(@skill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Language Exchange Nicosia</h1>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_user_session_path(@user) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_user_registration_path(@user) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_user_password_path(@user) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(@user) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(@user) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(@user, provider) %><br />
  <% end -%>
<% end -%>